version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    restart: always
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Rooms
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4321rewq
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=Rooms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4321rewq
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"